from datetime import date,datetime
from decimal import Decimal
from sqlalchemy import Boolean,Date,DateTime,ForeignKey,Integer,Numeric,String,Text
from sqlalchemy.orm import Mapped,mapped_column
from .database import Base
class User(Base):
    __tablename__="users";user_id:Mapped[int]=mapped_column(Integer,primary_key=True);full_name:Mapped[str]=mapped_column(String(120));email:Mapped[str]=mapped_column(String(180),unique=True);password_hash:Mapped[str]=mapped_column(String(300));role:Mapped[str]=mapped_column(String(20));phone:Mapped[str|None]=mapped_column(String(25),nullable=True);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Property(Base):
    __tablename__="properties";property_id:Mapped[int]=mapped_column(Integer,primary_key=True);owner_id:Mapped[int]=mapped_column(ForeignKey("users.user_id"));title:Mapped[str]=mapped_column(String(180));description:Mapped[str]=mapped_column(Text);property_type:Mapped[str]=mapped_column(String(40));city:Mapped[str]=mapped_column(String(100));area:Mapped[str]=mapped_column(String(120));address:Mapped[str|None]=mapped_column(Text,nullable=True);latitude:Mapped[float|None]=mapped_column(Numeric(10,7),nullable=True);longitude:Mapped[float|None]=mapped_column(Numeric(10,7),nullable=True);monthly_rent:Mapped[Decimal]=mapped_column(Numeric(12,2));bedrooms:Mapped[int]=mapped_column(Integer);bathrooms:Mapped[int]=mapped_column(Integer);furnished:Mapped[bool]=mapped_column(Boolean,default=False);image_url:Mapped[str|None]=mapped_column(Text,nullable=True);status:Mapped[str]=mapped_column(String(20),default="AVAILABLE");created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Booking(Base):
    __tablename__="bookings";booking_id:Mapped[int]=mapped_column(Integer,primary_key=True);property_id:Mapped[int]=mapped_column(ForeignKey("properties.property_id"));tenant_id:Mapped[int]=mapped_column(ForeignKey("users.user_id"));start_date:Mapped[date]=mapped_column(Date);end_date:Mapped[date|None]=mapped_column(Date,nullable=True);monthly_rent:Mapped[Decimal]=mapped_column(Numeric(12,2));booking_amount:Mapped[Decimal]=mapped_column(Numeric(12,2));status:Mapped[str]=mapped_column(String(20),default="PENDING");created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Payment(Base):
    __tablename__="payments";payment_id:Mapped[int]=mapped_column(Integer,primary_key=True);booking_id:Mapped[int]=mapped_column(ForeignKey("bookings.booking_id"));amount:Mapped[Decimal]=mapped_column(Numeric(12,2));payment_method:Mapped[str]=mapped_column(String(30),default="DEMO");transaction_ref:Mapped[str|None]=mapped_column(String(180),unique=True,nullable=True);status:Mapped[str]=mapped_column(String(20),default="PENDING");paid_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True)
class RentalContract(Base):
    __tablename__="rental_contracts";contract_id:Mapped[int]=mapped_column(Integer,primary_key=True);booking_id:Mapped[int]=mapped_column(ForeignKey("bookings.booking_id"),unique=True);contract_number:Mapped[str]=mapped_column(String(80),unique=True);terms:Mapped[str]=mapped_column(Text);tenant_signed:Mapped[bool]=mapped_column(Boolean,default=False);owner_signed:Mapped[bool]=mapped_column(Boolean,default=False);contract_status:Mapped[str]=mapped_column(String(20),default="DRAFT");created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class Activity(Base):
    __tablename__="activities";activity_id:Mapped[int]=mapped_column(Integer,primary_key=True);user_id:Mapped[int|None]=mapped_column(ForeignKey("users.user_id"),nullable=True);action:Mapped[str]=mapped_column(String(120));description:Mapped[str|None]=mapped_column(Text,nullable=True);created_at:Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
